-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- vim.api.nvim_create_autocmd("ColorScheme", {
--   group = vim.api.nvim_create_augroup("wezterm_colorscheme", { clear = true }),
--   callback = function(args)
--     local colorschemes = {
--       ["solarized"] = "Builtin Solarized Light",
--       ["tokyonight-day"] = "Tokyo Night Day",
--       ["tokyonight-storm"] = "Tokyo Night Storm",
--       ["catppuccin-frappe"] = "Catppuccin Frappe",
--       ["catppuccin-latte"] = "Catppuccin Latte",
--       ["catppuccin-macchiato"] = "Catppuccin Macchiato",
--       ["catppuccin-mocha"] = "Catppuccin Mocha",
--       ["gruvbox"] = "GruvboxDark",
--       -- add more color schemes here ...
--     }
--     local colorscheme = colorschemes[args.match]
--     if not colorscheme then
--       return
--     end
--     -- Write the colorscheme to a file
--     local filename = vim.fn.expand("$HOME/.config/wezterm/colorscheme")
--     assert(type(filename) == "string")
--     local file = io.open(filename, "w")
--     assert(file)
--     file:write(colorscheme)
--     file:close()
--     vim.notify("Setting WezTerm color scheme to " .. colorscheme, vim.log.levels.INFO)
--   end,
-- })
