k9s:
  cluster: gerulata-android-cluster
  namespace:
    active: fb-mobile
    lockFavorites: false
    favorites:
    - kube-system
    - container-registry
    - all
    - fb-mobile
  view:
    active: deploy
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
