k9s:
  cluster: production-cluster
  skin: red
  namespace:
    active: tiktok-new
    lockFavorites: false
    favorites:
    - daq
    - imageboard-dev
    - imageboard
    - tiktok-new
  view:
    active: deploy tiktok-new
  featureGates:
    nodeShell: false
  portForwardAddress: localhost
